// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/ControlMessage.proto

package org.apache.hudi.connect;

public interface ControlMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:connect.ControlMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 protocolVersion = 1;</code>
   */
  int getProtocolVersion();

  /**
   * <code>.connect.ControlMessage.EventType type = 2;</code>
   */
  int getTypeValue();
  /**
   * <code>.connect.ControlMessage.EventType type = 2;</code>
   */
  org.apache.hudi.connect.ControlMessage.EventType getType();

  /**
   * <code>string topic_name = 3;</code>
   */
  java.lang.String getTopicName();
  /**
   * <code>string topic_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getTopicNameBytes();

  /**
   * <code>.connect.ControlMessage.EntityType sender_type = 4;</code>
   */
  int getSenderTypeValue();
  /**
   * <code>.connect.ControlMessage.EntityType sender_type = 4;</code>
   */
  org.apache.hudi.connect.ControlMessage.EntityType getSenderType();

  /**
   * <code>uint32 sender_partition = 5;</code>
   */
  int getSenderPartition();

  /**
   * <code>.connect.ControlMessage.EntityType receiver_type = 6;</code>
   */
  int getReceiverTypeValue();
  /**
   * <code>.connect.ControlMessage.EntityType receiver_type = 6;</code>
   */
  org.apache.hudi.connect.ControlMessage.EntityType getReceiverType();

  /**
   * <code>uint32 receiver_partition = 7;</code>
   */
  int getReceiverPartition();

  /**
   * <code>string commitTime = 8;</code>
   */
  java.lang.String getCommitTime();
  /**
   * <code>string commitTime = 8;</code>
   */
  com.google.protobuf.ByteString
      getCommitTimeBytes();

  /**
   * <code>.connect.ControlMessage.CoordinatorInfo coordinator_info = 9;</code>
   */
  boolean hasCoordinatorInfo();
  /**
   * <code>.connect.ControlMessage.CoordinatorInfo coordinator_info = 9;</code>
   */
  org.apache.hudi.connect.ControlMessage.CoordinatorInfo getCoordinatorInfo();
  /**
   * <code>.connect.ControlMessage.CoordinatorInfo coordinator_info = 9;</code>
   */
  org.apache.hudi.connect.ControlMessage.CoordinatorInfoOrBuilder getCoordinatorInfoOrBuilder();

  /**
   * <code>.connect.ControlMessage.ParticipantInfo participant_info = 10;</code>
   */
  boolean hasParticipantInfo();
  /**
   * <code>.connect.ControlMessage.ParticipantInfo participant_info = 10;</code>
   */
  org.apache.hudi.connect.ControlMessage.ParticipantInfo getParticipantInfo();
  /**
   * <code>.connect.ControlMessage.ParticipantInfo participant_info = 10;</code>
   */
  org.apache.hudi.connect.ControlMessage.ParticipantInfoOrBuilder getParticipantInfoOrBuilder();

  public org.apache.hudi.connect.ControlMessage.PayloadCase getPayloadCase();
}
